In [8]:
#Import libraries needed
import numpy
import time
from array import array

#Funtion uses numpy array
def numpy_array(n):
    start_time = time.time()

    #Creating empty numpy array
    p = numpy.empty(n)

    #Assigning value to each element
    for i in range(n):
        p[i] = i
    end_time = time.time()

    #Calculating time difference
    return end_time - start_time

#Function uses python array
def python_array(n):
    start_time = time.time()

    #Creating python array
    p = array('d')

    #Assigning value to each element
    for i in range(n):
        p.append(i)
    end_time = time.time()

    #Calculating time difference
    return end_time - start_time

print('NumPy Array time :',round(numpy_array(10000000),2),' Sec.')
print('Python Array time :',round(python_array(10000000),2), ' Sec.')

NumPy Array time : 1.01  Sec.
Python Array time : 1.62  Sec.


In [9]:
import numpy as np 
import time 
size_of_vec = 1000000 

def python_list_v():
    start_time = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X))]
    return time.time() - start_time
def numpy_array_v():
    start_time = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y 
    return time.time() - start_time
print('NumPy Array time :',round(numpy_array_v(),2),' Sec.')
print('Python List time :',round(python_list_v(),2), ' Sec.')

NumPy Array time : 0.01  Sec.
Python List time : 0.33  Sec.


In [13]:
# Creating an array
arr = np.array([1,2,3])
print("rank1 array", arr)

arr = np.array([[1,2,3],[4, 5, 6]])
print("rank 2 array", arr)

arr = np.array((1,2,3))
print("array of tupel", arr)

rank1 array [1 2 3]
rank 2 array [[1 2 3]
 [4 5 6]]
array of tupel [1 2 3]


In [14]:
# Array indexing
arr = np.array([[1,2,3,4], 
                [5,-6,7,-8], 
                [9,10,-11,-12]]) 
sliced_array = arr[1:,::2]
print ("Array with last 2 rows and alternate columns ", sliced_array) 

integer_indexing_array  = arr[[0,1,2],[3,2,1]]
print ("Elements at indices (0, 3), (1, 2), (2, 1): ", integer_indexing_array) 

# boolean array indexing
condition = arr > 2
boolean_indexing_array = arr[condition] 
print ("Elements greater than 2:  ", boolean_indexing_array) 


Array with last 2 rows and alternate columns  [[  5   7]
 [  9 -11]]
Elements at indices (0, 3), (1, 2), (2, 1):  [ 4  7 10]
Elements greater than 2:   [ 3  4  5  7  9 10]


In [19]:
# Basic array operations
#first array
import numpy as np 

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
#addition
sum_of_array = np.add(arr1, arr2)
print("addition of two arrays",sum_of_array)

# Addition of all Array elements
sum_array_elements = numpy.sum(arr1)
print("addition of all array",sum_array_elements)

#Trace of Array
trace_array = np.trace(arr1)
print('trace of array',trace_array)

# Square root of Array
sqrt_arry = numpy.sqrt(arr1)
print("\nSquare root of Array1 elements: ",sqrt_arry)
 
# Transpose of Array
trans_arry = arr1.T
print("Transpose of Array: ",trans_arry)

addition of two arrays [[ 6  8]
 [10 12]]
addition of all array 10
trace of array 5

Square root of Array1 elements:  [[1.         1.41421356]
 [1.73205081 2.        ]]
Transpose of Array:  [[1 3]
 [2 4]]


In [23]:
# How can we extract numbers within a range from a NumPy array?
import numpy as np
arr = numpy.arange(20)
# Using where
index = np.where((arr >= 7) & (arr<= 14))
print(arr[index]) 

# using logical end
index = np.where(np.logical_and(arr >= 7, arr<=14))
print(arr[index])
 # using conditions on array 
    
new_arr = arr[(arr >= 7) & (arr <= 14)] 
print(new_arr)

[ 7  8  9 10 11 12 13 14]
[ 7  8  9 10 11 12 13 14]
[ 7  8  9 10 11 12 13 14]


In [24]:
#How can we reverse NumPy array elements?
import numpy as np 
arr = np.arange(5)
print('Original Array:  ', arr)
rev_arr = arr[::-1]
print('Reversed Array:  ',rev_arr)

Original Array:   [0 1 2 3 4]
Reversed Array:   [4 3 2 1 0]


In [25]:
#mapping each category to a number
import numpy as np 
category = ['Small','Large','Medium','Large','Medium','Small','Small']
category_array = np.array(category)
print('Categorical Array:  ',category_array) 
label_map = {'Small': 1, 'Medium': 2, 'Large': 3} 
numeric_array = numpy.array([label_map[x] for x in category_array])
print('Numerical Array: ',numeric_array)



Categorical Array:   ['Small' 'Large' 'Medium' 'Large' 'Medium' 'Small' 'Small']
Numerical Array:  [1 3 2 3 2 1 1]


In [27]:
#How can we find the maximum value in each row and column of a NumPy 2d array?
import numpy as np
arr = np.array([[1,2,3,4], 
                [5,-6,7,-8], 
                [9,10,-11,-12]])
print("max value in row", np.amax(arr,axis = 1))
print("max value in column", np.amax(arr,axis=0))

max value in row [ 4  7 10]
max value in column [ 9 10  7  4]
